### ISSUE TITLE
Review front end models

### ISSUE THREAD

**Issue by andrii-i** [jupyter-server/jupyter-scheduler#105]
> What's confusing is that `model.jobsView = 'ListJobs'` will render either the job list or the job definition list, dispatching based on `model.listJobsModel.listJobsView`.
>
> @andrii-i For now, you'll want to somehow set the `listJobsView` to `'JobDefinitionDetail'` immediately after line 29 above.
>
> @jweill-aws We need to have a more thorough discussion on the purpose of these models. To my recollection, the whole point of models as a global state store was to allow persistence (serialization to JSON in local storage) and rehydration upon page reload. However, the list jobs view really doesn't have any state that needs to be persisted. Whether the jobs list or the job definitions list is being rendered should be stored in `model.jobsView` rather than inside `model.listJobsModel.listJobsView`, which means `model.listJobsModel` can be deleted entirely.
>
> Another refactoring suggestion, rename `JobsModel` => `SchedulerModel` and `model.jobsView` => `model.view`.

_Originally posted by @dlqqq in https://github.com/jupyter-server/jupyter-scheduler/pull/92#discussion_r990302770_

**Comment by ellisonbg** [comment]
@jweill-aws not sure I am following. I think that when the user has the list view open, if they reload the page, the list view should show exactly the same thing. For now, that is showing jobs or job definitions in the tab. As such I think that information should also be in the global model and serialized. In the future, we will also want to serialize the column sorting information, and the search/fielder fields.

**Comment by andrii-i** [comment]
CC-ing @dlqqq (as an author of the quote based on which this issue was created) to @ellisonbg comment above

**Comment by dlqqq** [comment]
Renaming suggestions will be tracked in a separate issue here: https://github.com/jupyter-server/jupyter-scheduler/issues/210
