### ISSUE TITLE
User is not warned when deleting a job or job definition in Details view

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#107]
## Description

When the user clicks "Delete Job" or "Delete Job Definition" from the details view, the job or job definition is deleted immediately, with no confirmation step. This is irreversible.

## Expected behavior

The user should see a confirmation dialog (e.g., a modal) when they click a delete button so that they can confirm their decision to delete.

**Comment by ellisonbg** [comment]
Another option is to have a single button that is two-stage delete. The first click on the "X" would turn that button into a more prominent (and red) delete button, which when clicked would actually delete the job. iOS does this in places and it is a bit more lightweight than a full dialog, which would get cumbersome for in situations where you are deleting jobs often, but not using (the yet to be built) multi-selection batch actions.

**Comment by andrii-i** [comment]
Created #142 to track Deletion confirmation in List View in a way described by @ellisonbg above. Renamed this issue to clarify that it tracks Deletion confirmation in Details View using modal confirmation.
