### ISSUE TITLE
Job Definition Detail 2-column layout getting misaligned when schedule tooltip is long

### ISSUE THREAD

**Issue by andrii-i** [jupyter-server/jupyter-scheduler#110]
Steps to reproduce (courtesy of @dlqqq):
1. Pull from `main` and `build`
2. Run `python dev/seed.py` to populate your DB with seed data
3. Open job definitions table, click on some random job definitions until you find one with a long schedule. Notice the input box is too big.

Environment: 
Google Chrome Version 105.0.5195.125 (arm64)
![image](https://user-images.githubusercontent.com/26686070/194677875-53e3ac11-327e-4ba3-a9b6-dbfaab5180d1.png)

**Comment by jweill-aws** [comment]
Likely a similar underlying cause as #67. This only seems to happen on Chrome, not on Firefox.

**Comment by andrii-i** [comment]
> Likely a similar underlying cause as #67. This only seems to happen on Chrome, not on Firefox.

thank you, added
