### ISSUE TITLE
`runtime_environment_parameters` not propagated to JobDetail model

### ISSUE THREAD

**Issue by awaisabir** [jupyter-server/jupyter-scheduler#125]
## Description
It seems like we are not propagating the value for `runtime_environment_parameters` from the job detail API response to the front-end model being using. I believe we need to add this change in so a custom extension can display the runtime env params in the job details section: https://github.com/jupyter-server/jupyter-scheduler/blob/main/src/model.ts#L155

## Reproduce
- Fire a request for a job that has these parameters defined
- Observe that these params will not show up in the advanced options section for job details

## Expected behavior
These `runtime_environment_parameters` should be available for consumption when a job detail response is converted to the front end model passed to the advanced-options custom component(s)

## Context

- Operating System and version:
- Browser and version:
- Jupyter Server version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by andrii-i** [comment]
Looking into this

**Comment by andrii-i** [comment]
@awaisabir opened #126 to fix this
