### ISSUE TITLE
Incorrect schedule when simplified UI is used

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter-scheduler#129]
## Description

When a notebook is scheduled using the simplified scheduling UI (rather than cron) all jobs end up with the cron expression `0 0 * * MON-FRI` regardless of how the simplified UI is configured. Interestingly if you first use the simplified UI, then change to "Custom Interval" the correct cron expression is used.

## Reproduce

1. Create a notebook job using the simplified UI
2. Don't change to "Custom Interval" before creating the job.
3. Go to the Job Definition detail view and you will see the incorrect cron expression of `0 0 * * MON-FRI`.

## Expected behavior

Using the simplified schedule UI should always result in the correct cron expression, whether or not the user changes to "Custom Interval" or not.

**Comment by jweill-aws** [comment]
The default interval is 00:00 on weekdays, which maps to `0 0 * * MON-FRI` in cron. This is working as designed.

**Comment by jweill-aws** [comment]
When setting the schedule to "Every minute," then submitting, the `0 0 * * MON-FRI` schedule is present in the request:

```
{"name":"Untitled1.ipynb","input_uri":"Untitled1.ipynb","output_prefix":"","runtime_environment_name":"","schedule":"0 0 * * MON-FRI","timezone":"America/Los_Angeles"}
```
