### ISSUE TITLE
Full column set for job definition list view

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter-scheduler#133]
### Problem

Carrying over work from #81:

Here is the list of columns for the "Job Definitions" table:

- [x] Name
- [x] Link to open the Job Definition detail view.
- [x] Created time
- [x] Paused or not?
- [x] Summary of schedule (human readable)
- [x] Actions:
  - [x] Delete
  - [x] Pause/unpause

**Comment by jweill-aws** [comment]
Delete, pause, and unpause are added in #141.
