### ISSUE TITLE
Handle errors in server and UI at job creation time

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter-scheduler#147]
### Problem

There are a number of failure modes that may lead to a job not actually being created when the create job REST API is called. Some examples:

* The input file does does not exist.
* A job with the IT already exists (see #40)
* etc.

### Proposed Solution

* The server should return an appropriate HTTP error code and error message to the response body.
* The frontend should remain on the create view until the job is actually created.
* If a create error occurs the create view should render that and allow the user to fix it.

**Comment by 3coins** [comment]
@jweill-aws UI doesn't seem to work with errors from the API. The view becomes unstable when an error happens while creating a job. Can you pull out the main branch and test this on your end when you get a chance.

**Comment by 3coins** [comment]
Submitted a fix #167
