### ISSUE TITLE
store absolute paths for output files in DB

### ISSUE THREAD

**Issue by dlqqq** [jupyter-server/jupyter-scheduler#162]
### Problem

Storing job output directories as relative to the server root fails if the server is shut down and then started in a different directory.

### Proposed Solution

- when building the output directory path in the backend, store it in the DB as an absolute path
- when returning output file paths from the backend, always have it be relative to the server root

However, it's not clear how the backend would handle output file paths from entirely disjoint directories. Take the following directory structure:

```
/home/user/
|_ a/
|_ b/
```

If a job were created when `a/` was the server root, then when `b/` is the server root, how are those output paths returned from the backend? Files under `a/` are inaccessible to the ContentsManager and cannot be viewed via the JL UI when served from `b/`. I believe that in this case, the backend should just return the absolute file path and the frontend can handle the UI accordingly, via determining if the path is absolute or not. Perhaps greying out the output files link and then rendering a tooltip (cannot view files outside server root)?

**Comment by 3coins** [comment]
@dlqqq Does this still apply?

**Comment by dlqqq** [comment]
@3coins No, #189 will close this since job files will now always be downloaded relative to the current server root. In other words, changing server roots will make the REST API return `downloaded: false` for all jobs and then the user can re-download the files relative to their server root.

I will edit the PR description of #189 to auto-close this issue on merge.

**Comment by ellisonbg** [comment]
Closing, no longer relevant.
