### ISSUE TITLE
Editable/read-only state of Advanced Options in Job Definition Detail

### ISSUE THREAD

**Issue by andrii-i** [jupyter-server/jupyter-scheduler#165]
## Problem

The advanced options inputs will / might still be editable in the detail view.

## Proposed Solution

Editable/read-only state of `Jobs Definition` should also extend to edit-ability / read-only state of `AdvancedOptions` displayed on the page (as [mentioned](https://github.com/jupyter-server/jupyter-scheduler/pull/164#pullrequestreview-1146659868) by @dlqqq in #164). 

> Hmm, an obvious issue with this is that it appears the advanced options inputs will still be editable in the detail view. We should add a `readonly` boolean prop to the existing advanced options API to address this, but there's no need to do so at this very moment.

_Originally posted by @dlqqq in https://github.com/jupyter-server/jupyter-scheduler/pull/164#pullrequestreview-1146659868_
  
Part of #87

**Comment by dlqqq** [comment]
Closed by #207. See discussion in #224.
