### ISSUE TITLE
Use non-outlined text fields on job details / job definition details page

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#173]
### Problem

If we decide to repurpose the create form as an "edit job description" form (#172), then we should stop making the details view use outlined TextFields, which convey to the user that they are viewing a form they can edit.

### Proposed Solution

Use the non-outlined style of TextField, and of other MUI components, on the details view.

Alternatively, use a component that has no underline or border for read-only text display.

**Comment by andrii-i** [comment]
We should make sure Create View also aligns with "standard variant of text fields for non-editable fields and outlined for editable" convention

**Comment by jweill-aws** [comment]
Only one field in the create form is readonly (input field) so this could probably be made simultaneously

**Comment by andrii-i** [comment]
There's also invariant of EnvironmentPicker when there's just 1 environment. I'll change it and input field simultaneously

**Comment by andrii-i** [comment]
Preview:

![Screen Shot 2022-10-20 at 11 48 05 AM](https://user-images.githubusercontent.com/26686070/197068999-5345be27-aa41-4484-a59e-1649c7326629.png)
![Screen Shot 2022-10-20 at 3 13 15 PM](https://user-images.githubusercontent.com/26686070/197069137-f7eebfcb-57be-4fab-918e-45484a6244c7.png)
![Screen Shot 2022-10-20 at 3 13 39 PM](https://user-images.githubusercontent.com/26686070/197069147-a0a87c39-2cbc-43d5-a206-b50750528359.png)

**Comment by ellisonbg** [comment]
Users will recognize the alternate Material text field styling (the underlined version, with no outline) as an editable text field, just as much as the outlined version. We should build a simple component for this purpose that is further away from being an editable text field.

**Comment by andrii-i** [comment]
Preview using new component:
![Screen Shot 2022-10-21 at 5 05 13 PM](https://user-images.githubusercontent.com/26686070/197308377-23b9019d-ffad-495e-9d05-4bee29cd0f68.png)

**Comment by andrii-i** [comment]
Job Definition view with HelperText under Schedule field
![Screen Shot 2022-10-21 at 6 00 09 PM](https://user-images.githubusercontent.com/26686070/197309475-57e94192-2b03-4d92-bb53-d209b8dd2974.png)

**Comment by andrii-i** [comment]
Made LabeledValues tighter
![Screen Shot 2022-10-27 at 5 38 14 PM](https://user-images.githubusercontent.com/26686070/198422789-61b8d0b0-95b0-4b18-8bd5-e74d940b3beb.png)

**Comment by andrii-i** [comment]
Opened #220 based on this latest preview
