### ISSUE TITLE
UI unstable on error thrown from backend at job creation with schedule

### ISSUE THREAD

**Issue by 3coins** [jupyter-server/jupyter-scheduler#176]
## Description
Scheduler UI is unstable when an error happens when creating a job with a schedule.

![scheduled-job-failure](https://user-images.githubusercontent.com/289369/197086513-77cd1d51-c559-47e0-b7dd-60c7495121d6.gif)

On restart, UI is still unstable because of the state restoration of the UI in start.

## Reproduce
Select a file to create a job, and delete the file before submitting the job. This should cause the input error and make the UI unstable.

## Expected behavior
Backend errors produced while creating jobs with schedule should be shown on the top in a red banner and UI should continue to function and allow the user to re-submit the job.

## Context
Extension version: 0.5.1

**Comment by jweill-aws** [comment]
I tried to reproduce this as follows:

1. Right-click on file X in the file browser and choose "Create Notebook Job".
2. Set the job name.
3. Delete file X.
4. Click "Create."

I see, in the UI, "Input path 'X' does not exist." I can click "Cancel" to be brought to the jobs list.

![image](https://user-images.githubusercontent.com/93281816/197306135-6faeba81-bbff-4f12-b329-7fdcd02570ea.png)

**Comment by jweill-aws** [comment]
Closing; not reproducible with current code.
