### ISSUE TITLE
Users can confuse the rerun job icon with reloading/refreshing the view.

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter-scheduler#178]
### Problem

We are finding the users may be confused when they see the MUI replay icon in the list view to rerun a job. They think it will instead reload the list view state from the server. 

### Proposed Solution

Icon buttons are known to be ambiguous. Longer term we may move away from icon buttons in the list view rows altogether, but in the meantime, we should reconsider the icon for rerunning a job.

**Comment by jweill-aws** [comment]
Should the ["Create/Edit" icon](https://mui.com/material-ui/material-icons/?query=write&selected=Create) ✏️ be used instead of the reload icon used today?

**Comment by jweill-aws** [comment]
Resolving as "won't fix" because the "rerun job" button will be removed.

**Comment by jweill-aws** [comment]
See #192 for removal of rerun job button.
