### ISSUE TITLE
Indicate that a job is being created after the user clicks "Create"

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter-scheduler#179]
### Problem

When a user clicks the "Create" button to create a job, we stay on the job creation form until the server returns that the job has successfully been created. Once the job is created, we navigate to the list view. During the intermediate state, we should visually indicate to the user that the job/dob def is being created.

### Proposed Solution

We might consider using a green panel level notification banner for this purpose. That way, when we show an error upon job creation, users would be looking there.

**Comment by jweill-aws** [comment]
Alternative proposal: disable the "Create" button after a user clicks it, then re-enable it if there's an error that causes the user to remain on the create jobs page.

**Comment by awaisabir** [comment]
Might be useful to show some sort of loading state on the Create button + a disabled state, to indicate that there is an asynchronous operation happening
