### ISSUE TITLE
Don't show environment when only 1 option

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter-scheduler#191]
### Problem

Where there is only 1 environment, we should pick that one and completely hide the environment dropdown in the create form.

**Comment by jweill-aws** [comment]
Keep in mind that we don't know at create-job form load time whether there is 1 or more environments available. After I make this change, the environments picker will first display "Loading …" and then disappear.

**Comment by jweill-aws** [comment]
@ellisonbg Should I also hide "output formats" in this case?
