### ISSUE TITLE
Create docs for users, developers

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#200]
### Problem

Users do not know, clearly, how to install Jupyter Scheduler. Developers do not know how to extend it.

### Proposed Solution

Write documentation, for hosting on ReadTheDocs, for user and developer use cases.

### Additional context

Installation, extension points, scheduling (UI and API).

**Comment by misolietavec** [comment]
Maybe, it would be better to postpone 1.0 release to the time when the minimal user documentation is done? Usually, 1.0 implies also stable documentation...

**Comment by ellisonbg** [comment]
We plan on working on the documentation soon.

**Comment by jweill-aws** [comment]
Closing per #311; we now have [docs on ReadTheDocs](https://jupyter-scheduler.readthedocs.io/en/latest/). If you find errors or missing info, please file additional info. Thanks to @dlqqq for creating our first docs on ReadTheDocs!
