### ISSUE TITLE
Indicate job creation error if there is a parameter with empty key and value

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter-scheduler#208]
## Description

If a user clicks on the "+" button to create a parameter, but leaves both the key and value empty, that is passed to the REST API which may lead to problems.

## Reproduce

1. Create a job.
2. Click on the "+" to add a parameter.
3. Leave the key and value empty.
4. Create the job.

No error messages is given to the user and the job is created with an empty parameters.

## Expected behavior

Having a parameter with an empty key and value should show an error message to the user and block job creation.

**Comment by jweill-aws** [comment]
Per @ellisonbg , rejects "key and no value" as invalid.

https://user-images.githubusercontent.com/93281816/198684546-4e4829da-0a03-41a2-9f0b-b5d0d8485f30.mov
