### ISSUE TITLE
A user can create a job without picking an environment and things crash

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter-scheduler#231]
## Description

By default, there is no environment selected. If a user creates a job without first selecting an environment, no validation error shows, the job fails to create, and the panel becomes empty.

## Reproduce

1. Create a job on a system with multiple environments.
2. Don't pick an environment.
3. Create the job.
4. Panel becomes empty..

## Expected behavior

A validation error should show below the environment picker if one is not selected, and we should block job creation until they select one.

**Comment by jweill-aws** [comment]
As discussed earlier today: we should select the first environment by default, as we do with compute types (in the absence of a default c.t.). Submitting with no environment selected is not a good idea.
