### ISSUE TITLE
Input notebook link move from "Job files" to "Input filename" column

### ISSUE THREAD

**Issue by edwardps** [jupyter-server/jupyter-scheduler#242]
### Problem
The input notebook download link is listed in the job files column. There is dedicated column called "input filename". Please see the uploaded screenshot. 
It would be more natural to reuse the input filename column to show the input notebook. 

### Proposed Solution
When the input notebook is downloaded, change the text input name to link. 

<img width="774" alt="Screen Shot 2022-10-31 at 5 03 06 PM" src="https://user-images.githubusercontent.com/83920185/199131429-941aea84-1b85-44b1-bd20-0998274328be.png">

**Comment by ellisonbg** [comment]
This is a nice idea, we are also going to remove the file extension from the default job name to show users that the name doesn't have to just be the full file name and extension.
