### ISSUE TITLE
refactor ScheduleInputs component

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#251]
## Description

When the schedule starts as `0 0 15 * *` (00:00 on the 15th of the month):

![image](https://user-images.githubusercontent.com/93281816/199329452-2fce3777-6c7a-492d-9a86-2e617236eba0.png)

… and then the user switches to "Month" scheduling:

![image](https://user-images.githubusercontent.com/93281816/199329717-c47505b0-c0e3-4fd4-91a1-7f38803209c0.png)

… the day of the month does not propagate to the input, but the time does.

## Reproduce

1. Schedule is 0 0 15 * *  (00:00 on the 15th of the month)
2. Click "Edit job definition"
3. Drop down "Interval," pick "Month"
4. Error: "Day of the month" is blank

## Expected behavior

Day of the month should be "15".

## Context

Found while validating #238.

**Comment by jweill-aws** [comment]
This is likely because state is duplicated.

Another side effect of this: setting the time to be invalid, and then changing the create form from "create job definition" to "create job" causes the time error to continue to block the form, but it shouldn't:


https://user-images.githubusercontent.com/93281816/199365112-8ee2dc3d-9393-4e7d-99a7-14088e62c51d.mov

**Comment by dlqqq** [comment]
This is fixed by #261, but now validation errors are no longer reinstated after switching back to "run on a schedule". We think this is fine for now, as the edge case of an invalid cron expression is caught by the backend anyways, and is much better than the fatal possibility of being unable to create jobs.

**Comment by jweill-aws** [comment]
Errors not being reinstated are covered by #262.
