### ISSUE TITLE
How to handle job failures and job outputs?

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter-scheduler#257]
### Problem

There are two types of job failures:

1. Full/major/fatal failure that causes the job to not run at all, only a log might be available.
2. A notebook cell raises an exception, but all outputs are still available.

### Proposed Solution

Modify the logic in the backend and UI to allow job files to be included in the success and failure state and to allow backends to include a subset of files in the downloading.

**Comment by 3coins** [comment]
Fixed by #270
