### ISSUE TITLE
Handling API Errors in Jobs List View UI

### ISSUE THREAD

**Issue by zuoyuanh** [jupyter-server/jupyter-scheduler#263]
### Problem

Currently, we do show error messages in UI when we got errors from POST API when submitting/creating notebook jobs in Create Job view. However, we don't display descriptive error messages in Jobs List/Job Definitions List view for HTTP errors (https://github.com/jupyter-server/jupyter-scheduler/blob/main/src/components/advanced-table/advanced-table.tsx#L98) and we just render an empty list instead. This is not ideal for the errors that are actionable for customers (for example, refreshing expired credentials, etc., or reach out us for investigation/fixes if this is because of a bug). 

### Proposed Solution

* Similar to Create Jobs view, start with showing simple error messages from API response if the status code is not 200 OK, or generic error message if there is a network error. 
  * In the ideal case we can make this error rendering logic an extensible interface so other plugins that extends scheduler can customize this error handling logic as they need. 

### Additional context

* Currently, in Jobs List/Job Definitions list view, we don't show error message if underlying API to get jobs/job definitions fail. We render an empty list, same as there is no jobs. Customer can't tell if this is due to there is no jobs, or some errors, and may not have ideas on the action they can take:
  * ![Screen Shot 2022-11-02 at 9 04 02 AM](https://user-images.githubusercontent.com/15898408/199541902-277c65dd-3ae6-47f0-a661-d2af3ae651da.png)
* In comparison, we render the error we got from API call (https://github.com/jupyter-server/jupyter-scheduler/blob/main/jupyter_scheduler/scheduler.py#L379) in UI when creating notebook jobs, so customers are clear on the action they can take to fix it:
  * ![Screen Shot 2022-11-02 at 9 11 48 AM](https://user-images.githubusercontent.com/15898408/199542301-093ebac9-6a39-4736-8cf1-c225d8233481.png)

**Comment by jweill-aws** [comment]
Thank you for your contribution! We can pick up this issue.
