### ISSUE TITLE
When input notebook is located in a subfolder the input file link could not be shown properly. 

### ISSUE THREAD

**Issue by edwardps** [jupyter-server/jupyter-scheduler#274]
## Description
If customer use a notebook from a subfolder rather the Jupyter home folder. After the job output is downloaded, input link could not be displayed properly. 

## Reproduce

Simply use a notebook in any subfolder. 
<img width="768" alt="Screen Shot 2022-11-03 at 5 21 33 PM" src="https://user-images.githubusercontent.com/83920185/199859166-35400a2d-82c4-45c0-a1a0-4cf2d8f830dc.png">

**Comment by ellisonbg** [comment]
Thanks @edwardps we will have a look.

**Comment by edwardps** [comment]
Feel free to resolve if it's not caused by OSS extension. Seems the issue is caused by integration with OSS extension(not OSS issue).

**Comment by dlqqq** [comment]
Yes, this issue looks like it's being caused by your custom backend implementation not downloading the input file on download.
