### ISSUE TITLE
Let developers override "Run Now" API endpoint

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#28]
### Problem

Developers would like to call a different API when "Run Now" is clicked.

### Proposed Solution

Let developers override the "Run Now" action to call a different API.

### Additional context

<!-- Add any other context or screenshots about the feature request here. You can also include links to examples of other programs that have something similar to your request. For example:

* Another project [...] solved this by [...]

**Comment by ellisonbg** [comment]
What is the usage case here? The REST API is already fully customizable. Isn't the answer for someone to override the backend implementation.

**Comment by jweill-aws** [comment]
Closing per @ellisonbg
