### ISSUE TITLE
Job definition creation failure due to validation error and show weird error message 

### ISSUE THREAD

**Issue by edwardps** [jupyter-server/jupyter-scheduler#281]
## Description
When the job is created using an invalid s3 bucket(e.g. s3 bucket in another different region), the job will be failed due to backend validation. Then the UI show error message like below: 

```
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Error%3A%20S3%20bucket%20-us-west-2%20must%20be%20in%20region%20'us-east-1'%2C%20but%20found%20in%20'us-west-2' for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

## Reproduce
Simply use a s3 bucket in different region.

**Comment by dlqqq** [comment]
Interesting, it looks like we are rendering the error object itself rather than the text? I don't see why this would be the case in #277. I'll investigate this issue further on Monday.

<img width="903" alt="Screen Shot 2022-11-04 at 6 04 42 PM" src="https://user-images.githubusercontent.com/44106031/200094215-4357680f-9e56-49e5-948e-7b03c4956477.png">

**Comment by edwardps** [comment]
Thanks David for the investigation. 

Can we follow the behavior and show the error message in the job creation page? This enable customer to easily fix the issue without requiring entering configuration from scratch.

**Comment by jweill-aws** [comment]
I have not been able to reproduce this. I tried to replace `createJob` with a function that always fails:

```
  async createJob(
    model: Scheduler.ICreateJob
  ): Promise<Scheduler.ICreateJobResponse> {
    return Promise.reject(
      new ServerConnection.ResponseError(
        new Response(),
        'Rejected because I said so'
      )
    );
  }
``` 

When I submit a request, I always get an error message above the form, without hitting the error boundary.

![image](https://user-images.githubusercontent.com/93281816/200428991-b535ea7f-04db-4145-8e02-36960bcaf207.png)

In `submitCreateJobRequest`, we're already using a try/catch block to catch this error, so it wouldn't hit the error boundary anyway:

https://github.com/jupyter-server/jupyter-scheduler/blob/795e702bb5bb4ddd2057a235d9f729188f3de1b2/src/mainviews/create-job.tsx#L333-L345

**Comment by jweill-aws** [comment]
I can reproduce this in open source code with a custom handler for job definition creation, but not with one for job creation. A similar try/catch block appears in the `submitCreateJobDefinitionRequest` function.
