### ISSUE TITLE
Add "CREATED" and "QUEUED" states, creation time to job runs

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#3]
### Problem

We want to show the most newly-created jobs at the top of the jobs list. Jobs have a start date and we sort the jobs list by default in descending order by start date.

The problem is that newly-created jobs are in state "STOPPED" with no start date, so they appear at the bottom (not at the top) of the jobs list by default.

### Proposed Solution

Add two additional states for jobs to be in: "CREATED" and "QUEUED", both of which indicate that a job has not yet started.

Add a creation date/time for each job.

Sort the jobs list, by default, in descending order by creation date/time.

### Additional context

Should we add the creation date/time to the jobs list so that users can sort by it?

**Comment by ellisonbg** [comment]
Closing as fixed in main.
