### ISSUE TITLE
Add happy-case walkthroughts to user docs

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#319]
### Problem

The ["Users" docs](https://jupyter-scheduler.readthedocs.io/en/latest/users/index.html) for Jupyter Scheduler only cover installation, not usage.

### Proposed Solution

Add descriptions, with screen shots, of what users can do with Jupyter Scheduler and how they can do it.

### Additional context

This is a follow-up to #311, which created ReadTheDocs docs.

**Comment by andrii-i** [comment]
Fixed by #323
