### ISSUE TITLE
Unable to run scheduler after installation

### ISSUE THREAD

**Issue by kuanseongyeoh** [jupyter-server/jupyter-scheduler#350]
## Unable to run scheduler after installation

Jupyter server extension shows error of juypter_scheduler when listing out.
Also the option is not available to run the schedule
![image](https://user-images.githubusercontent.com/75087608/223194174-7007a5a4-5e1e-4fcb-8f69-36b267bc330c.png)
<img width="346" alt="image" src="https://user-images.githubusercontent.com/75087608/223194322-799b605a-11c9-4c2e-9683-398ebbfab4b5.png">

Running on Windows 10 Enterprise, Anaconda Jupyter Lab 3.5.0

**Comment by JasonWeill** [comment]
On a Windows 10 computer (x86-64, virtual machine), I was unable to reproduce this. Here are the steps I followed:

1. Install Miniconda for Windows
2. Open a miniconda terminal
3. Run `conda install jupyterlab` (JupyterLab 3.5.3 installed)
4. Run `pip install jupyter-scheduler`
5. Run `jupyter lab`
6. Both the lab extension and the server extension were running.
