### ISSUE TITLE
Scheduler unable to run if the ipynb content contains quotation mark

### ISSUE THREAD

**Issue by kuanseongyeoh** [jupyter-server/jupyter-scheduler#353]
## Description

Scheduler unable to run if the ipynb content contains quotation mark “ ” 

## Reproduce

Once the quotation mark are removed, the scheduler runs successfully. Yet it will be great if the owner can debug this or at least specifically call out the character causing the trouble

**Comment by 3coins** [comment]
@kuanseongyeoh 
Thanks for opening this issue. Can you add details about your environment, which platform and JupyterLab version you are using? Also, can you paste the error from the terminal where JupyterLab is running.

**Comment by andrii-i** [comment]
@kuanseongyeoh thank you for creating this. Would "ipynb content" (that needs to contain quotation marks to cause the problem) in this case be any cell?

**Comment by JasonWeill** [comment]
OP is using Windows. This bug might be in the `open` function, which may presume Windows-1252 as the charset on Windows, where 0x9d doesn't refer to anything; we might need to explicitly specify , encoding='utf-8' to avoid this, per this SO post:
https://stackoverflow.com/questions/49562499/how-to-fix-unicodedecodeerror-charmap-codec-cant-decode-byte-0x9d-in-posit

**Comment by 3coins** [comment]
@kuanseongyeoh 
I have submitted a fix in #354, can you try pulling this branch and testing on your machine.

**Comment by 3coins** [comment]
@kuanseongyeoh 
Did you have a chance to verify this change?

**Comment by kuanseongyeoh** [comment]
![image](https://user-images.githubusercontent.com/75087608/225228494-d779c81d-3d2b-47e6-b28f-0d5e72fe0669.png)
No luck, still doesn't work. Installed the latest version 1.3.1, put back the character “ ” but still no luck.
![image](https://user-images.githubusercontent.com/75087608/225228668-c63edba2-2d25-4a9b-a5cc-52afe1228f81.png)

**Comment by dlqqq** [comment]
You will want to run:

```
git clone git@github.com:jupyter-server/jupyter-scheduler.git
cd jupyter-scheduler/ # <= replace this with whatever command is needed on Windows to enter a dir
git remote add origin 3coins git@github.com:3coins/jupyter-scheduler.git
git fetch 3coins
git checkout fix-encoding
pip install -e .
```

Then try it again.
