### ISSUE TITLE
ERROR: No matching distribution found for jupyter_scheduler

### ISSUE THREAD

**Issue by otavio-s-s** [jupyter-server/jupyter-scheduler#363]
I have a jupyterlab running inside a container on a linux virtual machine, which works just fine for everything I need. Howeever, I'm failing to install jupyter scheduler as you can see below:

```
# pip install jupyter_scheduler
ERROR: Could not find a version that satisfies the requirement jupyter_scheduler (from versions: none)
ERROR: No matching distribution found for jupyter_scheduler
```

When I try to install the extension in the extension ta, I get this:

![image](https://user-images.githubusercontent.com/60897189/228556548-60bdee3c-a635-42b0-bd2d-c2f01c872084.png)

Versions:

```
# pip show jupyter
Name: jupyter
Version: 1.0.0
Summary: Jupyter metapackage. Install all the Jupyter components in one go.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.org
License: BSD
Location: /usr/local/lib/python3.6/dist-packages
Requires: ipykernel, ipywidgets, jupyter-console, nbconvert, notebook, qtconsole
Required-by: 
# pip show jupyterlab
Name: jupyterlab
Version: 3.2.9
Summary: JupyterLab computational environment
Home-page: https://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: UNKNOWN
Location: /usr/local/lib/python3.6/dist-packages
Requires: ipython, jinja2, jupyter-core, jupyter-server, jupyterlab-server, nbclassic, packaging, tornado
Required-by: 
# pip  --version
pip 21.3.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
```

**Comment by JasonWeill** [comment]
Hi @otavio-s-s , thanks for opening this issue! It looks like you're using an unsupported version of Python (3.6 reached end of life on 2021-12-23) and an older version of JupyterLab (the newest maintained version is 3.6.2). Do you still see this problem when you upgrade both?

**Comment by otavio-s-s** [comment]
Hi @JasonWeill, yes that worked, thank you!
