### ISSUE TITLE
Cannot delete jobs in Safari browser

### ISSUE THREAD

**Issue by ChaonengQuan** [jupyter-server/jupyter-scheduler#364]
## Description

I cannot delete notebook jobs in Safari browser. However, if I open jupyter lab in Firefox then notebook jobs can be deleted.

## Reproduce

1. Create a conda environment  `conda create -n py310 python=3.10 -y`
2. Activate the condo environment `conda activate py310`
3. Install jupyter lab and jupyter scheduler `pip install jupyter_scheduler jupyterlab`
4. Start jupyter lab `jupyter lab`
5. Create a notebook jobs and try to delete it by clicking on the delete button
<img width="1484" alt="Screen Shot 2023-03-31 at 10 27 27 AM" src="https://user-images.githubusercontent.com/46586569/229189272-daf15e47-2735-483e-a51d-6000e4c014c9.png">
6. Delete button not working as I cannot delete notebook jobs

## Expected behavior
Notebook jobs can be deleted by the Delete button

## Context

- Operating System and version: MacOS Version 12.6.3 (21G419)
- Browser and version: Safari Version 16.3 (17614.4.6.11.6, 17614)
- Jupyter Server version: 
```
jupyter --version 
Selected Jupyter core packages...
IPython          : 8.12.0
ipykernel        : 6.22.0
ipywidgets       : not installed
jupyter_client   : 8.1.0
jupyter_core     : 5.3.0
jupyter_server   : 2.5.0
jupyterlab       : 3.6.3
nbclient         : 0.7.2
nbconvert        : 7.2.10
nbformat         : 5.8.0
notebook         : 6.5.3
qtconsole        : not installed
traitlets        : 5.9.0
```

<details><summary>Troubleshoot Output</summary>
<pre>
❯ jupyter troubleshoot
$PATH:
        /Users/chaoneng/.nvm/versions/node/v14.21.3/bin
        /opt/homebrew/opt/ruby/bin
        /opt/homebrew/Caskroom/miniconda/base/envs/py310/bin
        /opt/homebrew/Caskroom/miniconda/base/condabin
        /opt/homebrew/bin
        /opt/homebrew/sbin
        /usr/local/bin
        /usr/bin
        /bin
        /usr/sbin
        /sbin
        /Users/chaoneng/.fig/bin
        /Users/chaoneng/.local/bin
        /Users/chaoneng/Library/Application Support/JetBrains/Toolbox/scripts
        /Users/chaoneng/.toolbox/bin
        /Users/chaoneng/.local/bin

sys.path:
        /opt/homebrew/Caskroom/miniconda/base/envs/py310/bin
        /opt/homebrew/Caskroom/miniconda/base/envs/py310/lib/python310.zip
        /opt/homebrew/Caskroom/miniconda/base/envs/py310/lib/python3.10
        /opt/homebrew/Caskroom/miniconda/base/envs/py310/lib/python3.10/lib-dynload
        /Users/chaoneng/.local/lib/python3.10/site-packages
        /opt/homebrew/Caskroom/miniconda/base/envs/py310/lib/python3.10/site-packages

sys.executable:
        /opt/homebrew/Caskroom/miniconda/base/envs/py310/bin/python

sys.version:
        3.10.10 (main, Mar 21 2023, 13:41:05) [Clang 14.0.6 ]

platform.platform():
        macOS-12.6.3-arm64-arm-64bit

which -a jupyter:
        /opt/homebrew/Caskroom/miniconda/base/envs/py310/bin/jupyter

pip list:
        Package                  Version
        ------------------------ ---------
        aiobotocore              2.4.2
        aiofiles                 22.1.0
        aiohttp                  3.8.4
        aioitertools             0.11.0
        aiosignal                1.3.1
        aiosqlite                0.18.0
        anyio                    3.6.2
        appnope                  0.1.3
        argon2-cffi              21.3.0
        argon2-cffi-bindings     21.2.0
        arrow                    1.2.3
        astroid                  2.15.0
        asttokens                2.2.1
        async-timeout            4.0.2
        attrs                    22.2.0
        autopep8                 1.6.0
        Babel                    2.12.1
        backcall                 0.2.0
        beautifulsoup4           4.12.0
        bleach                   6.0.0
        botocore                 1.27.59
        certifi                  2022.12.7
        cffi                     1.15.1
        charset-normalizer       3.1.0
        comm                     0.1.3
        croniter                 1.3.8
        debugpy                  1.6.6
        decorator                5.1.1
        defusedxml               0.7.1
        dill                     0.3.6
        docstring-to-markdown    0.11
        executing                1.2.0
        fastjsonschema           2.16.3
        flake8                   6.0.0
        fqdn                     1.5.1
        frozenlist               1.3.3
        fsspec                   2023.3.0
        idna                     3.4
        ipykernel                6.22.0
        ipython                  8.12.0
        ipython-genutils         0.2.0
        isoduration              20.11.0
        isort                    5.12.0
        jedi                     0.18.2
        Jinja2                   3.1.2
        jmespath                 1.0.1
        json5                    0.9.11
        jsonpointer              2.3
        jsonschema               4.17.3
        jupyter_client           8.1.0
        jupyter_core             5.3.0
        jupyter-events           0.6.3
        jupyter_scheduler        1.3.1
        jupyter_server           2.5.0
        jupyter_server_fileid    0.8.0
        jupyter_server_terminals 0.4.4
        jupyter_server_ydoc      0.8.0
        jupyter-ydoc             0.2.3
        jupyterlab               3.6.3
        jupyterlab-pygments      0.2.2
        jupyterlab_server        2.22.0
        lazy-object-proxy        1.9.0
        MarkupSafe               2.1.2
        matplotlib-inline        0.1.6
        mccabe                   0.7.0
        mistune                  2.0.5
        multidict                6.0.4
        nbclassic                0.5.4
        nbclient                 0.7.2
        nbconvert                7.2.10
        nbformat                 5.8.0
        nest-asyncio             1.5.6
        notebook                 6.5.3
        notebook_shim            0.2.2
        packaging                23.0
        pandocfilters            1.5.0
        parso                    0.8.3
        pexpect                  4.8.0
        pickleshare              0.7.5
        pip                      23.0.1
        platformdirs             3.2.0
        prometheus-client        0.16.0
        prompt-toolkit           3.0.38
        psutil                   5.9.4
        ptyprocess               0.7.0
        pure-eval                0.2.2
        pycodestyle              2.10.0
        pycparser                2.21
        pydantic                 1.10.7
        pydocstyle               6.2.3
        pyflakes                 3.0.1
        Pygments                 2.14.0
        pylint                   2.17.0
        pyrsistent               0.19.3
        python-dateutil          2.8.2
        python-json-logger       2.0.7
        python-lsp-jsonrpc       1.0.0
        python-lsp-server        1.7.1
        pytoolconfig             1.2.5
        pytz                     2023.3
        PyYAML                   6.0
        pyzmq                    25.0.2
        requests                 2.28.2
        rfc3339-validator        0.1.4
        rfc3986-validator        0.1.1
        rope                     1.7.0
        s3fs                     2023.3.0
        Send2Trash               1.8.0
        setuptools               65.6.3
        six                      1.16.0
        sniffio                  1.3.0
        snowballstemmer          2.2.0
        soupsieve                2.4
        SQLAlchemy               1.4.47
        stack-data               0.6.2
        terminado                0.17.1
        tinycss2                 1.2.1
        tomli                    2.0.1
        tomlkit                  0.11.6
        tornado                  6.2
        traitlets                5.9.0
        typing_extensions        4.5.0
        ujson                    5.7.0
        uri-template             1.2.0
        urllib3                  1.26.15
        wcwidth                  0.2.6
        webcolors                1.13
        webencodings             0.5.1
        websocket-client         1.5.1
        whatthepatch             1.0.4
        wheel                    0.38.4
        wrapt                    1.15.0
        y-py                     0.5.9
        yapf                     0.32.0
        yarl                     1.8.2
        ypy-websocket            0.8.2

conda list:
        # packages in environment at /opt/homebrew/Caskroom/miniconda/base/envs/py310:
        #
        # Name                    Version                   Build  Channel
        aiobotocore               2.4.2                    pypi_0    pypi
        aiofiles                  22.1.0                   pypi_0    pypi
        aiohttp                   3.8.4                    pypi_0    pypi
        aioitertools              0.11.0                   pypi_0    pypi
        aiosignal                 1.3.1                    pypi_0    pypi
        aiosqlite                 0.18.0                   pypi_0    pypi
        anyio                     3.6.2                    pypi_0    pypi
        appnope                   0.1.3                    pypi_0    pypi
        argon2-cffi               21.3.0                   pypi_0    pypi
        argon2-cffi-bindings      21.2.0                   pypi_0    pypi
        arrow                     1.2.3                    pypi_0    pypi
        asttokens                 2.2.1                    pypi_0    pypi
        async-timeout             4.0.2                    pypi_0    pypi
        attrs                     22.2.0                   pypi_0    pypi
        babel                     2.12.1                   pypi_0    pypi
        backcall                  0.2.0                    pypi_0    pypi
        beautifulsoup4            4.12.0                   pypi_0    pypi
        bleach                    6.0.0                    pypi_0    pypi
        botocore                  1.27.59                  pypi_0    pypi
        bzip2                     1.0.8                h620ffc9_4  
        ca-certificates           2023.01.10           hca03da5_0  
        certifi                   2022.12.7       py310hca03da5_0  
        cffi                      1.15.1                   pypi_0    pypi
        charset-normalizer        3.1.0                    pypi_0    pypi
        comm                      0.1.3                    pypi_0    pypi
        croniter                  1.3.8                    pypi_0    pypi
        debugpy                   1.6.6                    pypi_0    pypi
        decorator                 5.1.1                    pypi_0    pypi
        defusedxml                0.7.1                    pypi_0    pypi
        executing                 1.2.0                    pypi_0    pypi
        fastjsonschema            2.16.3                   pypi_0    pypi
        fqdn                      1.5.1                    pypi_0    pypi
        frozenlist                1.3.3                    pypi_0    pypi
        fsspec                    2023.3.0                 pypi_0    pypi
        idna                      3.4                      pypi_0    pypi
        ipykernel                 6.22.0                   pypi_0    pypi
        ipython                   8.12.0                   pypi_0    pypi
        ipython-genutils          0.2.0                    pypi_0    pypi
        isoduration               20.11.0                  pypi_0    pypi
        jedi                      0.18.2                   pypi_0    pypi
        jinja2                    3.1.2                    pypi_0    pypi
        jmespath                  1.0.1                    pypi_0    pypi
        json5                     0.9.11                   pypi_0    pypi
        jsonpointer               2.3                      pypi_0    pypi
        jsonschema                4.17.3                   pypi_0    pypi
        jupyter-client            8.1.0                    pypi_0    pypi
        jupyter-core              5.3.0                    pypi_0    pypi
        jupyter-events            0.6.3                    pypi_0    pypi
        jupyter-scheduler         1.3.1                    pypi_0    pypi
        jupyter-server            2.5.0                    pypi_0    pypi
        jupyter-server-fileid     0.8.0                    pypi_0    pypi
        jupyter-server-terminals  0.4.4                    pypi_0    pypi
        jupyter-server-ydoc       0.8.0                    pypi_0    pypi
        jupyter-ydoc              0.2.3                    pypi_0    pypi
        jupyterlab                3.6.3                    pypi_0    pypi
        jupyterlab-pygments       0.2.2                    pypi_0    pypi
        jupyterlab-server         2.22.0                   pypi_0    pypi
        libffi                    3.4.2                hca03da5_6  
        markupsafe                2.1.2                    pypi_0    pypi
        matplotlib-inline         0.1.6                    pypi_0    pypi
        mistune                   2.0.5                    pypi_0    pypi
        multidict                 6.0.4                    pypi_0    pypi
        nbclassic                 0.5.4                    pypi_0    pypi
        nbclient                  0.7.2                    pypi_0    pypi
        nbconvert                 7.2.10                   pypi_0    pypi
        nbformat                  5.8.0                    pypi_0    pypi
        ncurses                   6.4                  h313beb8_0  
        nest-asyncio              1.5.6                    pypi_0    pypi
        notebook                  6.5.3                    pypi_0    pypi
        notebook-shim             0.2.2                    pypi_0    pypi
        openssl                   1.1.1t               h1a28f6b_0  
        packaging                 23.0                     pypi_0    pypi
        pandocfilters             1.5.0                    pypi_0    pypi
        parso                     0.8.3                    pypi_0    pypi
        pexpect                   4.8.0                    pypi_0    pypi
        pickleshare               0.7.5                    pypi_0    pypi
        pip                       23.0.1          py310hca03da5_0  
        platformdirs              3.2.0                    pypi_0    pypi
        prometheus-client         0.16.0                   pypi_0    pypi
        prompt-toolkit            3.0.38                   pypi_0    pypi
        psutil                    5.9.4                    pypi_0    pypi
        ptyprocess                0.7.0                    pypi_0    pypi
        pure-eval                 0.2.2                    pypi_0    pypi
        pycparser                 2.21                     pypi_0    pypi
        pydantic                  1.10.7                   pypi_0    pypi
        pygments                  2.14.0                   pypi_0    pypi
        pyrsistent                0.19.3                   pypi_0    pypi
        python                    3.10.10              hc0d8a6c_2  
        python-dateutil           2.8.2                    pypi_0    pypi
        python-json-logger        2.0.7                    pypi_0    pypi
        pytz                      2023.3                   pypi_0    pypi
        pyyaml                    6.0                      pypi_0    pypi
        pyzmq                     25.0.2                   pypi_0    pypi
        readline                  8.2                  h1a28f6b_0  
        requests                  2.28.2                   pypi_0    pypi
        rfc3339-validator         0.1.4                    pypi_0    pypi
        rfc3986-validator         0.1.1                    pypi_0    pypi
        s3fs                      2023.3.0                 pypi_0    pypi
        send2trash                1.8.0                    pypi_0    pypi
        setuptools                65.6.3          py310hca03da5_0  
        six                       1.16.0                   pypi_0    pypi
        sniffio                   1.3.0                    pypi_0    pypi
        soupsieve                 2.4                      pypi_0    pypi
        sqlalchemy                1.4.47                   pypi_0    pypi
        sqlite                    3.41.1               h80987f9_0  
        stack-data                0.6.2                    pypi_0    pypi
        terminado                 0.17.1                   pypi_0    pypi
        tinycss2                  1.2.1                    pypi_0    pypi
        tk                        8.6.12               hb8d0fd4_0  
        tomli                     2.0.1                    pypi_0    pypi
        tornado                   6.2                      pypi_0    pypi
        traitlets                 5.9.0                    pypi_0    pypi
        typing-extensions         4.5.0                    pypi_0    pypi
        tzdata                    2022g                h04d1e81_0  
        uri-template              1.2.0                    pypi_0    pypi
        urllib3                   1.26.15                  pypi_0    pypi
        wcwidth                   0.2.6                    pypi_0    pypi
        webcolors                 1.13                     pypi_0    pypi
        webencodings              0.5.1                    pypi_0    pypi
        websocket-client          1.5.1                    pypi_0    pypi
        wheel                     0.38.4          py310hca03da5_0  
        wrapt                     1.15.0                   pypi_0    pypi
        xz                        5.2.10               h80987f9_1  
        y-py                      0.5.9                    pypi_0    pypi
        yarl                      1.8.2                    pypi_0    pypi
        ypy-websocket             0.8.2                    pypi_0    pypi
        zlib                      1.2.13               h5a0b063_0

conda env:
        name: py310
        channels:
          - defaults
        dependencies:
          - bzip2=1.0.8=h620ffc9_4
          - ca-certificates=2023.01.10=hca03da5_0
          - certifi=2022.12.7=py310hca03da5_0
          - libffi=3.4.2=hca03da5_6
          - ncurses=6.4=h313beb8_0
          - openssl=1.1.1t=h1a28f6b_0
          - pip=23.0.1=py310hca03da5_0
          - python=3.10.10=hc0d8a6c_2
          - readline=8.2=h1a28f6b_0
          - setuptools=65.6.3=py310hca03da5_0
          - sqlite=3.41.1=h80987f9_0
          - tk=8.6.12=hb8d0fd4_0
          - tzdata=2022g=h04d1e81_0
          - wheel=0.38.4=py310hca03da5_0
          - xz=5.2.10=h80987f9_1
          - zlib=1.2.13=h5a0b063_0
          - pip:
              - aiobotocore==2.4.2
              - aiofiles==22.1.0
              - aiohttp==3.8.4
              - aioitertools==0.11.0
              - aiosignal==1.3.1
              - aiosqlite==0.18.0
              - anyio==3.6.2
              - appnope==0.1.3
              - argon2-cffi==21.3.0
              - argon2-cffi-bindings==21.2.0
              - arrow==1.2.3
              - asttokens==2.2.1
              - async-timeout==4.0.2
              - attrs==22.2.0
              - babel==2.12.1
              - backcall==0.2.0
              - beautifulsoup4==4.12.0
              - bleach==6.0.0
              - botocore==1.27.59
              - cffi==1.15.1
              - charset-normalizer==3.1.0
              - comm==0.1.3
              - croniter==1.3.8
              - debugpy==1.6.6
              - decorator==5.1.1
              - defusedxml==0.7.1
              - executing==1.2.0
              - fastjsonschema==2.16.3
              - fqdn==1.5.1
              - frozenlist==1.3.3
              - fsspec==2023.3.0
              - idna==3.4
              - ipykernel==6.22.0
              - ipython==8.12.0
              - ipython-genutils==0.2.0
              - isoduration==20.11.0
              - jedi==0.18.2
              - jinja2==3.1.2
              - jmespath==1.0.1
              - json5==0.9.11
              - jsonpointer==2.3
              - jsonschema==4.17.3
              - jupyter-client==8.1.0
              - jupyter-core==5.3.0
              - jupyter-events==0.6.3
              - jupyter-scheduler==1.3.1
              - jupyter-server==2.5.0
              - jupyter-server-fileid==0.8.0
              - jupyter-server-terminals==0.4.4
              - jupyter-server-ydoc==0.8.0
              - jupyter-ydoc==0.2.3
              - jupyterlab==3.6.3
              - jupyterlab-pygments==0.2.2
              - jupyterlab-server==2.22.0
              - markupsafe==2.1.2
              - matplotlib-inline==0.1.6
              - mistune==2.0.5
              - multidict==6.0.4
              - nbclassic==0.5.4
              - nbclient==0.7.2
              - nbconvert==7.2.10
              - nbformat==5.8.0
              - nest-asyncio==1.5.6
              - notebook==6.5.3
              - notebook-shim==0.2.2
              - packaging==23.0
              - pandocfilters==1.5.0
              - parso==0.8.3
              - pexpect==4.8.0
              - pickleshare==0.7.5
              - platformdirs==3.2.0
              - prometheus-client==0.16.0
              - prompt-toolkit==3.0.38
              - psutil==5.9.4
              - ptyprocess==0.7.0
              - pure-eval==0.2.2
              - pycparser==2.21
              - pydantic==1.10.7
              - pygments==2.14.0
              - pyrsistent==0.19.3
              - python-dateutil==2.8.2
              - python-json-logger==2.0.7
              - pytz==2023.3
              - pyyaml==6.0
              - pyzmq==25.0.2
              - requests==2.28.2
              - rfc3339-validator==0.1.4
              - rfc3986-validator==0.1.1
              - s3fs==2023.3.0
              - send2trash==1.8.0
              - six==1.16.0
              - sniffio==1.3.0
              - soupsieve==2.4
              - sqlalchemy==1.4.47
              - stack-data==0.6.2
              - terminado==0.17.1
              - tinycss2==1.2.1
              - tomli==2.0.1
              - tornado==6.2
              - traitlets==5.9.0
              - typing-extensions==4.5.0
              - uri-template==1.2.0
              - urllib3==1.26.15
              - wcwidth==0.2.6
              - webcolors==1.13
              - webencodings==0.5.1
              - websocket-client==1.5.1
              - wrapt==1.15.0
              - y-py==0.5.9
              - yarl==1.8.2
              - ypy-websocket==0.8.2
        prefix: /opt/homebrew/Caskroom/miniconda/base/envs/py310
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
N/A
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
N/A

</pre>
</details>

**Comment by JasonWeill** [comment]
Still reproducible in JupyterLab 3.6.4, newest Jupyter Scheduler, and Safari version 16.5 (17615.2.9.11.6, 17615).
