### ISSUE TITLE
Improved idempotency token messaging

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#40]
### Problem

From looking at the code, here's how I'm reading the idempotency token (IT) logic:

1. Customer creates job with IT=`abc`. Job is created with ID `def`.
2. Customer creates job with IT=`abc`. Job is **not** created and ID `def` is returned.

This is confusing because, without any warning or error message, the user is brought to the job list page where the IT is not displayed prominently.

### Proposed Solution

Provide a warning message that is displayed on non-creation, as above, due to IT conflict.

In the UI, interpret this warning message and provide a link to view the job details for the job with IT=`def`.

### Additional context

This is a follow up to #33.

**Comment by ellisonbg** [comment]
Server should provide an error in the create job response that allows the frontend to handle this case.

**Comment by ellisonbg** [comment]
Leaving open, but will be fixed when #147 is fixed.

**Comment by jweill-aws** [comment]
Should be fixed by #146 (@3coins has a PR)

**Comment by jweill-aws** [comment]
Closing per @3coins
