### ISSUE TITLE
After I installed jupyter-scheduler, the kernel switching of jupyter lab failed

### ISSUE THREAD

**Issue by wxtt522** [jupyter-server/jupyter-scheduler#405]
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version:
- Browser and version:
- Jupyter Server version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by andrii-i** [comment]
Hi @wxtt522! Thank you for creating this issue. Could you please fill out the issue body template providing more information about the problem?

**Comment by wxtt522** [comment]
@andrii-i Thanks for your reply, it's a problem with my settings, this plugin can be timed to perform tasks from other env
