### ISSUE TITLE
Support for packaging dependency files

### ISSUE THREAD

**Issue by andrii-i** [jupyter-server/jupyter-scheduler#407]
### Problem

Currently there is no way to submit dependencies for a job run

### Proposed Solution

Provide ability to include multiple input files for a single job, but only one file that gets "run". Another way of phrasing this: specify both a directory and some "main" file as an input file.

**Comment by bhadrip** [comment]
We would like to have this feature for 1.X also, we cannot upgrade to JL4 yet. Ability to provide additional files is one of the most requested feature in SageMaker Studio.
