### ISSUE TITLE
Pytest failure in main (after #388 was merged) and #418

### ISSUE THREAD

**Issue by andrii-i** [jupyter-server/jupyter-scheduler#420]
## Description

- Build CI workflow fails due to Pytest `jupyter_scheduler/tests/test_job_files_manager.py:125` failure after changes in main (after #388 was merged) and #418. 

## Reproduce

See CI run : https://github.com/jupyter-server/jupyter-scheduler/actions/runs/5837424752/job/15832930590

**Comment by JasonWeill** [comment]
The underlying issue seems to be that when using the archiving scheduler, the "output" filenames are not used; the tarball contains files named with "staging" filenames. This does not cause a problem when run in production, but it breaks the tests. See #421 for a possible fix.
