### ISSUE TITLE
Telemetry 

### ISSUE THREAD

**Issue by sravyasdh** [jupyter-server/jupyter-scheduler#432]
### Problem

Would like to have a way to track button clicks/ change events of UI components for telemetry.

### Proposed Solution

A plugin which we can use in `amazon-sagemaker-jupyter-scheduler` extension to track these events. The plugin must accept a generic `panorama` method that is bound on the window as an argument. For example:
```js
if (window && window.panorama) {
    window.panorama(...);
}
```
### Additional context

We need to call the telemetry function for any click/change events in creating/ managing job workflows <br>

**Comment by dlqqq** [comment]
Closed by #448.
