### ISSUE TITLE
On Safari browser, the jobs section for in JobDefintion page is not visible

### ISSUE THREAD

**Issue by funnypenguine** [jupyter-server/jupyter-scheduler#449]
## Reproduce

1. Create a scheduled job, say, run a notebook untitled.ipynb every 2 minutes
2. After a few minutes when jobs are run, go to Job Definition page
3. On Chrome browser, you will see jobs that were started by this definition. On Safari, there is no jobs loaded. Both browsers are pointing to the same jupyterlab http://localhost:8888/lab

**Comment by funnypenguine** [comment]
<img width="1008" alt="Screenshot 2023-10-28 at 9 06 26 PM" src="https://github.com/jupyter-server/jupyter-scheduler/assets/149284535/aea6008f-fd24-4d66-8465-553db43c05dc">

**Comment by funnypenguine** [comment]
<img width="1094" alt="Screenshot 2023-10-28 at 9 47 03 PM" src="https://github.com/jupyter-server/jupyter-scheduler/assets/149284535/89c8372f-6166-411d-9683-115ad4e1c476">

**Comment by funnypenguine** [comment]
<img width="1020" alt="Screenshot 2023-10-28 at 9 46 49 PM" src="https://github.com/jupyter-server/jupyter-scheduler/assets/149284535/956dd9ac-a11a-45f0-bb7f-8bd3c2cb315d">

**Comment by JasonWeill** [comment]
@funnypenguine Thank you for opening this issue! What versions of Safari and macOS are you running? In addition, do you see any errors in Safari's developer tools console when you load a job definition detail view?

**Comment by funnypenguine** [comment]
Thanks, @JasonWeill. Do you know when this can go in? I tested the fix locally and it worked.

**Comment by JasonWeill** [comment]
@funnypenguine I'm coordinating with my team to ensure that this fix doesn't introduce any regressions with Safari or other browsers. Thanks for your patience!
