### ISSUE TITLE
Emit telemetry events on create job forms

### ISSUE THREAD

**Issue by sravyasdh** [jupyter-server/jupyter-scheduler#471]
### Problem
Would like to have telemetry data emitted for `Compute type` dropdown on create job page, and also for success / failure events after clicking on create job button. 

### Proposed Solution
1. When a compute type is selected using the dropdown, the click event along with the selected compute type will be logged using the `useEventLogger` hook.
2. In the case of successful job creation or job failure, the success/failure event is logged using the `useEventLogger` hook.

**Comment by JasonWeill** [comment]
This is a follow-up to #432, fixed by #448.

**Comment by dlqqq** [comment]
Per private conversation:

- Telemetry in the "compute type" dropdown has to be implemented in the extension providing that component in the Advanced Options section.
- However, we should emit telemetry events on success/failure for the **Create Job**, **Create Job Definition**, and **Create Job from Job Definition** forms.
