### ISSUE TITLE
Scheduler not working despite being installed and enabled

### ISSUE THREAD

**Issue by Padamire** [jupyter-server/jupyter-scheduler#473]
Hi guys

I recently installed Jupyter_Scheduler but was met with a pop up saying 'Jupyter Scheduler server extension not found', explaining the extension is installed but cannot be activated, as shown in the image below.
![image](https://github.com/jupyter-server/jupyter-scheduler/assets/105001309/118374a2-688c-427a-8434-1111d6f44dc0)

After following the recommendations, I ran mamba list to see the downloaded packages within anaconda, one of which was jupyter_scheduler v. 2.4.0. I then ran jupyter server extension list, which gave the following output.

![image](https://github.com/jupyter-server/jupyter-scheduler/assets/105001309/acefbee1-b0b1-4b6f-82b4-5a5763139b03)

Showing that jupyter scheduler's server extension is installed and enabled.

However, when I refresh the page, I get the same error popup saying that the scheduler is installed but not activated. 

I have seen a workaround at https://github.com/jupyterlab/jupyterlab/issues/8122 but they ask to delete the build-config.json file, which should be in JupyterLabs settings file, but the settings file is empty. 

Is there any way to fix this? I've tried every possible way: Installing from Pypi, running pip install instead of mamba install etc. I've burned countless hours trying to fix it and there never seems to be a solution.

- Browser: Chrome
- Jupyter Server version: Jupyter Lab 4.0.8

**Comment by JasonWeill** [comment]
@Padamire Thanks for opening this issue! It looks like you're using Windows. Can you share more info about your setup? (Windows version, whether you're using Windows Subsystem for Linux, etc)

**Comment by Padamire** [comment]
Hi Jason- I'm using Windows 11 (Version 22H2). I also have Anaconda Navigator installed to manage all my projects.

**Comment by JasonWeill** [comment]
I just tried to install Jupyter Scheduler 2.4.0 on my Windows machine (Windows 10, JupyterLab 4.0.8, Miniconda) using the [instructions for installation and verification](https://jupyter-scheduler.readthedocs.io/en/latest/users/index.html#installation), and I was successful. Do you see the same problem with a fresh Conda environment?

**Comment by JasonWeill** [comment]
As observed in https://github.com/jupyterlab/jupyterlab/issues/15658, you might have tried to install [jupyter**lab**_scheduler](https://github.com/tiburon-security/jupyterlab_scheduler), which is an unrelated extension. Please let us know if you still see this problem after going through the instructions linked above. Thanks!

**Comment by andrii-i** [comment]
Hi @Padamire. Were you able to check if you might have installed [jupyterlab_scheduler](https://github.com/tiburon-security/jupyterlab_scheduler) instead of `jupyter_scheduler`?

**Comment by andrii-i** [comment]
Closing as non-active. 

@Padamire, please check that you have `jupyter-scheduler`, not [jupyter**lab**_scheduler](https://github.com/tiburon-security/jupyterlab_scheduler) installed as discussed here and in https://github.com/jupyterlab/jupyterlab/issues/15658. If the problem still persists, please feel free to reopen the issue and send a (sanitized) output of `jupyter troubleshoot` command from your terminal.

**Comment by andrii-i** [comment]
Closing as non-active.

@Padamire, please check that you have jupyter-scheduler, not [jupyterlab_scheduler](https://github.com/tiburon-security/jupyterlab_scheduler) installed as discussed here and in https://github.com/jupyterlab/jupyterlab/issues/15658. If the problem still persists, please feel free to reopen the issue and send a (sanitized) output of jupyter troubleshoot command from your terminal.
