### ISSUE TITLE
Update Publishing Workflows

### ISSUE THREAD

**Issue by blink1073** [jupyter-server/jupyter-scheduler#495]
See https://github.com/jupyter-server/jupyter_releaser/pull/557 for background.

If y'all set up Trusted Publishing (https://pypi.org/manage/project/jupyter-scheduler/settings/publishing/#errors) for this repo, I can make a PR to update the workflows to use the Jupyter Server GitHub App for publishing.

- I have replaced the branch rules with  a branch "Ruleset"
- I added a tag Ruleset
- I configured the Release environment with appropriate credentials.

**Comment by andrii-i** [comment]
@blink1073 Thank you for upgrading workflows and creating this issue. 

JupyterLab PR for more context: https://github.com/jupyterlab/jupyterlab/pull/15973

**Comment by blink1073** [comment]
@Zsailer can you please add me (blink1073) to the project on pypi?  https://pypi.org/manage/project/jupyter-scheduler/collaboration/

**Comment by blink1073** [comment]
cc @3coins @dlqqq this is the last repo using a bot account.

**Comment by Zsailer** [comment]
I added you @blink1073! 😎 🚀
