### ISSUE TITLE
Add full-widget-sized job details view

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#5]
### Problem

Currently, the job details appears below the selected item in the jobs list. This multi-column layout doesn't leave enough room to display a lot of information. In addition, the column headers do not line up with the details in the inline details view. Users can expand multiple jobs' details at once, cluttering the list view.

### Proposed Solution

Add a details view that takes up the entire size of the list view's container (i.e., a main area widget). When the user clicks on a job name, they are brought to the details view. From the details view, a user can click a breadcrumb link to return to the list view.

Remove the details that appear below the row in the list.

### Additional context

We can also move the action buttons out of the list view and into the details view.

We can provide for an extension point, allowing developers to customize the details displayed in the details view.

Only one job's details can be viewed at a time.

**Comment by ellisonbg** [comment]
Closing as fixed in main.
