### ISSUE TITLE
Support of scheduling multiple notebooks with dependencies

### ISSUE THREAD

**Issue by nsingl00** [jupyter-server/jupyter-scheduler#517]
Current Jupyter Scheduler don't have a way to schedule multiple notebooks with dependencies in a pipeline/workflow.
Mostly data scientist and analyst have different set of notebooks doing different operations like data ingestion/feature engineering or creating and tuning ML models. It will be great if they can run a set of notebooks in single pipeline and schedule them to streamline their workflow lifecycle

**Comment by JasonWeill** [comment]
@nsingl00 Thank you for opening this issue! We have an existing issue covering this topic at #411. Let's keep the conversation going there.
