### ISSUE TITLE
Is it possible to query the list of jobs via terminal/API?

### ISSUE THREAD

**Issue by ajdajd** [jupyter-server/jupyter-scheduler#533]
I'm managing a handful of notebooks and would like to view their execution status in a different way. I thought interacting with the API would be a great place to start.

I've tried executing `curl -X GET "http://localhost:8888/scheduler/jobs"` but I'm getting a 404. Though I'm not really sure if this is the correct URL/port/endpoint. 

Any ideas how to do this or if it is even possible? Thanks!

**Comment by andrii-i** [comment]
Hi @ajdajd. Overall this request should work fine but it is missing authorization mechanism. Token authorization used by default would make request look like `curl -X GET "http://localhost:8888/scheduler/jobs?token=TOKENVALUE"`. Here's a Jupyter Server docs page on authorization / secutiry: https://jupyter-server.readthedocs.io/en/latest/operators/security.html. 

Please make sure that you have an instance of Jupyter Server running and that you are using correct address, correct port, and do authorization via token (or password if Jupyter Server is configured to authorize via password). 

You can run `jupyter lab` or `jupyter server` in terminal and one of the first messages printed in the terminal would have address, port, and token used by Jupyter Server:
```
[C 2024-07-03 17:22:00.301 ServerApp]

    To access the server, open this file in a browser:
        file:///Users/<...>
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=<...>
        http://127.0.0.1:8888/lab?token=<...>
```

**Comment by andrii-i** [comment]
Closing as answered but please feel free to ask follow-up questions.

**Comment by ajdajd** [comment]
Thank you very much for the detailed response! It pointed me to the right direction and I can get the data now :)

Documenting the steps here for posterity:
1. Enter `jupyter server list` to get the correct url and token. Add `/scheduler/jobs/` to the url.
2. Use a notebook to perform the GET request because the terminal won't show the response for some reason.

**Comment by andrii-i** [comment]
@ajdajd happy to hear that my response was helpful. 

Re (2) / the terminal not showing the response, note that `curl `does print responses by default. You can try experimenting with options such as `--verbose` (https://curl.se/docs/manpage.html#-v), `--include` (https://curl.se/docs/manpage.html#-i), `--output` (https://curl.se/docs/manpage.html#-o). 

Using a notebook works too. Another option is dedicated API development/testing software. Hoppscotch is a good open source option: https://github.com/hoppscotch/hoppscotch.
