### ISSUE TITLE
Remove pins on specific (and old) versions of pytz and fsspec

### ISSUE THREAD

**Issue by DManowitz** [jupyter-server/jupyter-scheduler#540]
The latest version of this package (currently 2.7.1) has dependencies on `pytz==2023.3` and `fsspec==2023.6.0`.  It is currently mid-August 2024.  Please verify that this package will work with more recent versions of these packages and unpin them from these specfic, old versions.

**Comment by andrii-i** [comment]
Hi @DManowitz. Thank you for creating this issue. This request makes sense and we are planning to update `pytz` and  `fsspec` version dependencies at some point but this is not a priority / we are not working on it now. At the same time, could you please share more about why / if Jupyter Scheduler not using latest versions of `pytz` and  `fsspec` is a problem / is a blocker for you?

**Comment by DManowitz** [comment]
Sorry, I have been busy and not responding to this has not been my highest priority, but @mbuechner said exactly what I would say.

**Comment by andrii-i** [comment]
Hi @mbuechner @DManowitz. Thank you for the feedback. Looking into updating `pytz` and `fsspec`.

**Comment by andrii-i** [comment]
Jupyter Scheduler 2.10.0 that includes support for latest versions of `fsspec` and `pytz` is released on PyPI and conda-forge 🚀
