### ISSUE TITLE
Add error messages to job details

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#55]
### Problem

Users want to view job run errors for every job they run.

### Proposed Solution

Make job run errors available in the API and make errors visible in the job details view.

**Comment by ellisonbg** [comment]
The job data model has a `status_message` field. Does this amount to rendering that field in the job detail view?

**Comment by dlqqq** [comment]
This issue describes output from job runs (i.e. stdout and stderr from a job process), but not the actual create job handler (https://github.com/jupyter-server/jupyter-scheduler/issues/122).

Per previous internal discussion in the team, job output will be stored in a separate output format that can be implemented via a custom `ExecutionManager`. Hence we are closing this issue for now.
