### ISSUE TITLE
Delete all button needed to purge all jobs tht have run.

### ISSUE THREAD

**Issue by vsr2158** [jupyter-server/jupyter-scheduler#550]
### Problem
No option to delete all jobs that have run.
Have to click x followed by 'DELETE' box to achieve the same.

No option to delete all jobs that have run.
Have to click x followed by 'DELETE' box to achieve the same.

### Proposed solution

Have a delete all under the notebook Jobs tab AND have same functionaly under the Job definiton tab to delete past run for a specific job definition.

**Comment by JasonWeill** [comment]
@vsr2158 Let's continue the discussion in #335. Also see #328.
