### ISSUE TITLE
Support fsspec 2024

### ISSUE THREAD

**Issue by LiutongZhou** [jupyter-server/jupyter-scheduler#555]
### Problem

As of `jupyter-scheduler==2.9.0`, `s3fs` and `fsspec` 2024 cannot be installed with `jupyter-scheduler` due to potential dependency conflict. `fsspec` is fixed to 2023.6.0 in https://github.com/jupyter-server/jupyter-scheduler/blob/1af9903a0671f2dfa570959bd097e6af492d9be0/pyproject.toml#L40

### Proposed solution

Relax the version pinning and support s3fs 2024

**Comment by andrii-i** [comment]
Hi @LiutongZhou. Thank you for creating this issue. I'm looking into updating fsspec.

**Comment by andrii-i** [comment]
Jupyter Scheduler 2.10.0 that includes support for latest versions of `fsspec` and `pytz` is released on PyPI and conda-forge 🚀
