### ISSUE TITLE
If input file has a directory, only the directory appears in the "input file" column

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#68]
## Description

If the input file for a notebook job has a relative path including a subdirectory, the "input" column shows only the subdirectory. The filename does not appear.

## Reproduce

1. Create a notebook job where the input file is in a subdirectory: `foo/bar.ipynb`.
2. View the jobs list.
3. The directory `foo`, but not the filename `bar.ipynb`, appears in the "Input file" column.

## Expected behavior

`foo/bar.ipynb` or `bar.ipynb` appears.

## Context

Seen in a 2022-09-30 demo.

**Comment by jweill-aws** [comment]
Screen shot:

![image](https://user-images.githubusercontent.com/93281816/193356713-ef9de5ce-51c8-4eb9-9ef3-7a63be74d90d.png)

**Comment by ellisonbg** [comment]
I thought we talked about making the input file non-editable in the UI. Given how users open the form if we introduce that constraints, we know that the file exists and is a valid path.

**Comment by ellisonbg** [comment]
See #78 for details on making the input file read only.

**Comment by jweill-aws** [comment]
This doesn't seem to be a problem in the OSS code; I just ran a file that is in a subdirectory, and in the "Input file" column, I see the filename without the directory. Closing.

![image](https://user-images.githubusercontent.com/93281816/194083453-9d0e326d-5169-4738-b203-9fbcb208e634.png)
