### ISSUE TITLE
Show Input File existence in field validation error

### ISSUE THREAD

**Issue by awaisabir** [jupyter-server/jupyter-scheduler#69]
### Problem

Currently we are showing an error if the user does not enter text in the `Input File` text field. This is a good first step, but there might be more validation needed to prevent user from entering malformed input.

### Proposed Solution

We can instead check for the existence of the file instead of "emptiness" for a better form of validation.

**Comment by ellisonbg** [comment]
Or maybe don't allow the user to edit the file? They already picked a valid file to get this form open...

**Comment by jweill-aws** [comment]
The input file parameter is no longer editable (see #78, #123) so I don't see the value in validating this field anymore. Closing.
