### ISSUE TITLE
JobDetail and buildTableRow have duplicate OutputFile element

### ISSUE THREAD

**Issue by andrii-i** [jupyter-server/jupyter-scheduler#75]
## Description

JobDetail and buildTableRow have duplicate OutputFile element

## Reproduce

1. Go to codebase
2. See OutputFile function in mainviews/job-detail.tsx and OutputFile function in components/job-row.tsx.
3. Note similarities

## Expected behavior

We should be able to reuse this code instead of duplicating it

## Context

- Operating System and version: N/A
- Browser and version: N/A
- Jupyter Server version: N/A

**Comment by dlqqq** [comment]
P.S. No need to fill out the whole form given for these small implementation details.

**Comment by jweill-aws** [comment]
Both functions are still present where mentioned in description

**Comment by jweill-aws** [comment]
These functions have diverged and are now `JobFiles` in `job-row.tsx` and `JobFile` in `job-detail.tsx`:

https://github.com/jupyter-server/jupyter-scheduler/blob/5f0c3ca88a7c494881b96e2ddb2619580fe35c33/src/components/job-row.tsx#L48-L79

https://github.com/jupyter-server/jupyter-scheduler/blob/5f0c3ca88a7c494881b96e2ddb2619580fe35c33/src/mainviews/detail-view/job-detail.tsx#L153-L177
