### ISSUE TITLE
Serialize full model and use in layout restoration

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter-scheduler#85]
The job panel has a model that is used to render the state of the view:

https://github.com/jupyter-server/jupyter-scheduler/blob/main/src/model.ts#L142

We should serialize this model to JSON by implementing a `toJSON` method and wire up that state to the JupyterLab layout restoration extension. This will improve usability by fully restoring the state of this panel when JupyterLab is reloaded.

**Comment by jweill-aws** [comment]
Closed by #158.
