### ISSUE TITLE
Enable Job Definitions to be edited

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter-scheduler#87]
### Problem

In our initial work on adding job scheduling, we probably won't get to making Job Definitions editable. This issue is to track that follow on work. 

### Proposed Solution

The list and detail view for a Job Definition should have an Edit action that allows the user to reconfigure elements of the scheduled job. See the REST API for which fields are editable:

https://github.com/jupyter-server/jupyter-scheduler/pull/45

**Comment by andrii-i** [comment]
@ellisonbg Some questions / consideration raised based on the discussion with @3coins and @dlqqq:

1. Editable fields. Which `Job Definition` fields should be editable? From API/backend perspective, any `Job Definition` field can be edited. Please also see point 3 for tangent discussion on if `Advanced options` should be shown and editable on `Job Detail Definition` page. @3coins suggested to start with `Schedule` and `Time zone` as editable fields as their edit-ability will bring the most value to users     
2. User flow needs clarification/validation/approval. Proposed user flow: 
- Add `Edit` button to `Job Definition Detail` button bar. When it is clicked, editable text fields become editable and button changes to `Save`. When `Save` is clicked, text fields become uneditable, changes to `Job Definition` are sent to the server and updated `Job Definition Detail` is shown
- Add `Edit` icon to `Job Definition List` icon bar. On click, `Job Definition Detail` in edit mode (with editable text fields described above opens up
3. Showing `Advanced options` in `Job Definition Detail`: currently `Advanced Options` are only shown at the bottom of `Job Detail` page. At the same time, as mentioned by @3coins, fields provided to `Advanced Options` might be / are meaningful for `Job Definition Detail` page too, especially if `Job Definition` can be edited as user might need to edit `Advanced Options` for `Job Definition` too. Created issue #160  to track this and facilitate discussion around it

**Comment by dlqqq** [comment]
From 10/20/2022 standup: Start with schedule and timezone being editable, add other fields afterwards upon receiving more user feedback.
