### ISSUE TITLE
Add a REST API to allow run now jobs from a job definition

### ISSUE THREAD

**Issue by 3coins** [jupyter-server/jupyter-scheduler#89]
### Problem
Users don't have a way to pick and existing job definition and submit a notebook job that would run immediately. 

### Proposed Solution
Add a REST API that allows a job definition and runtime parameters as inputs, and enables a run now job overriding the passed in attributes in the REST API.

### Additional context
https://github.com/jupyter-server/jupyter-scheduler/pull/45#discussion_r986902477

**Comment by ellisonbg** [comment]
Won't implement, closing.
