### ISSUE TITLE
Improve placeholder text for Output prefix in job creation form

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter-scheduler#94]
### Problem

The create job API takes an `output_prefix` argument that determines in which directory the output files will be put when the job completes. Currently the `TextField` placeholder for this UI element reads "Output prefix". We should improve that to give the user more useful information with example. This information should include:

* What the output prefix is (where output files will go)
* What its format is (relative or absolute path)
* Default value
* Examples.

**Comment by jweill-aws** [comment]
@ellisonbg The field is now called "Output path"; I can add helper text to the text field

**Comment by ellisonbg** [comment]
I thought we were going to call it "Output directory" to emphasize that it isn't a path to a file.

**Comment by jweill-aws** [comment]
#143 now refers to this field as "Output directory" — I made this change days after I wrote the comment above.
