### ISSUE TITLE
Add toolbar button to create job from current notebook

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#96]
### Problem

Users may not know that they can create a job or job definition from the current notebook.

### Proposed Solution

In the current notebook, add a toolbar button to open the create-job form to create a job or job definition from the current notebook. As is the case when the user right-clicks on a file in the file browser, the form should be pre-populated based on the current notebook.

**Comment by jweill-aws** [comment]
Proposed insertion point after "Restart Kernel & Run All Cells …"

![image (4)](https://user-images.githubusercontent.com/93281816/195469488-70311ff4-7daf-4fc5-a3a5-eeb90b73b710.png)

**Comment by ellisonbg** [comment]
This should be to the right of the built-in default toolbar items, which I believe would be to the right of the code type dropdown.
